name: job_test_task
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  equatable: ^2.0.3
  geolocator: ^9.0.1
  fluttertoast: ^8.0.8
  flutter_bloc: ^7.3.1
  json_serializable: ^6.1.6
  json_annotation: ^4.4.0
  build_runner: ^2.1.10
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_app_name: ^0.1.0
 
  flutter_lints: ^1.0.0

flutter_app_name:
  name: "Weather Counter"

flutter:
  uses-material-design: true
